apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lab-cluster
  region: us-east-1
  version: "1.18"

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  id: "vpc-000000000000"
  cidr: "172.16.0.0/16"
  securityGroup: "sg-000000000000"
  subnets:
    private:
      us-east-1a: { id: subnet-000000000000 }
      us-east-1b: { id: subnet-000000000000 }
    public:
      us-east-1a: { id: subnet-000000000000 }
      us-east-1b: { id: subnet-000000000000 }
iam:
  serviceRoleARN: "arn:aws:iam::account_id:role/eks-cluster"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
