apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lab-cluster
  region: us-east-1
  version: "1.18"

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  publicAccessCIDRs: ["0.0.0.0/0", "0.0.0.0/0"]
  id: "vpc-000000000"
  cidr: "0.0.0.0/0"
  securityGroup: "sg-0db753ae6a85c5657"
  subnets:
    private:
      us-east-1a: { id: subnet-00000000 }
      us-east-1b: { id: subnet-00000000 }
    public:
      us-east-1a: { id: subnet-00000000 }
      us-east-1b: { id: subnet-00000000 }
iam:
  serviceRoleARN: "arn:aws:iam::account_id:role/eks-cluster"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
