---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lab-cluster
  region: us-east-1

nodeGroups:
  - name: spot
    labels: { role: workers }
    tags:
      Name: spot
      k8s.io/cluster-autoscaler/cluster_name: owned
      k8s.io/cluster-autoscaler/enabled: "true"
    minSize: 2
    maxSize: 100
    instancesDistribution:
      instanceTypes: ["m5.large", "m5a.large", "m5n.large", "m4.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 5
      spotAllocationStrategy: capacity-optimized
    privateNetworking: true
    asgMetricsCollection:
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances
    ssh:
      publicKeyName: "key"
    iam:
      instanceProfileARN: "arn:aws:iam::account_id:instance-profile/eks-node"
      instanceRoleARN: "arn:aws:iam::account_id:role/eks-node"
    securityGroups:
      attachIDs: ["sg-000000000"]
